language: node_js
node_js:
  - "10"
branches:
  only:
  - master
script:
  - npm install -g typescript
  - npm install
  - npm test
  - npm run build
  - npm run build-min
jobs:
  include:
    - stage: npm release
      node_js: "10"
      before_deploy:
        - cd dist
      deploy:
        provider: npm
        email: "eaz@acrylplatform.com"
        api_key: $AUTH_TOKEN
        skip_cleanup: true